import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  docs: [
    'overview',
    'install',
    {
      type: 'category',
      label: 'Getting Started',
      
      items: [
        'getting-started/first-pipeline',
        'getting-started/core-concepts-and-terminology',
        'user-guide/studio-app-ui-overview',
        'getting-started/pipelines-persistence',
        'component-development/adding-components',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      
      items: [
       'core-concepts/what-are-components',
       'core-concepts/understanding-inputs-outputs',
       'core-concepts/caching',
      ],
    },
    {
      type: 'category',
      label: 'Component Development',
      
      items: [
       'component-development/creating-components-generic',
       'component-development/creating-components',
       'component-development/in-app-editor',
       'component-development/published-components-library',

      ],
    },
    {
      type: 'category',
      label: 'References',
      
      items: [
        'component-development/oasis-cli-manual',
        'reference/schema',
      ],
    },

  ],
};

export default sidebars;
